"use strict";

const filas = document.querySelectorAll(".fila");
const id = document.getElementById("id");
const fecha = document.getElementById("parte_diariaM");
const seccion = document.getElementById("seccionM");
const estacion = document.getElementById("estacionM");
const tipo_aviso = document.getElementById("tipo_avisoM");
const solicitante = document.getElementById("solicitanteM");
const receptor = document.getElementById("receptorM");
const aprobador = document.getElementById("aprobadorM");
const hora_aviso = document.getElementById("hora_avisoM");
const hora_salida = document.getElementById("hora_salidaM");
const hora_llegada = document.getElementById("hora_llegadaM");
const hora_regreso = document.getElementById("hora_regresoM");
const municipio = document.getElementById("municipioM");
const localidad = document.getElementById("localidadM");
const direccion = document.getElementById("direccionM");
const material_paredes = document.getElementById("material_paredesM");
const material_techo = document.getElementById("material_techoM");
const material_piso = document.getElementById("material_pisoM");
const material_ventanas = document.getElementById("material_ventanasM");
const material_puertas = document.getElementById("material_puertasM");
const otros_materiales = document.getElementById("otros_materialesM");
const propietario = document.getElementById("propietarioM");
const valor_inmueble = document.getElementById("valor_inmuebleM");
const residenciados = document.getElementById("residenciadosM");
const ninos = document.getElementById("ninosM");
const adolescentes = document.getElementById("adolescentesM");
const adultos = document.getElementById("adultosM");
const informacion_adicional = document.getElementById("informacion_adicionalM");
const asegurado = document.getElementsByName("asegurado");
const aseguradora = document.getElementById("aseguradoraM");
const numero_poliza = document.getElementById("numero_polizaM");
const valor_asegurado = document.getElementById("valor_aseguradoM");
const valor_perdido = document.getElementById("valor_perdidoM");
const valor_salvado = document.getElementById("valor_salvadoM");
const fuente_ignicion = document.getElementById("fuente_ignicionM");
const causa_incendio = document.getElementById("causa_incendioM");
const lugar_inicio = document.getElementById("lugar_inicioM");
const lugar_fin = document.getElementById("lugar_finM");
const reignicion = document.getElementsByName("reignicion");
const tipo_combustible = document.getElementById("tipo_combustibleM");
const declaracion = document.getElementById("declaracionM");
const lesion = document.getElementsByName("lesion");
const numero_lesionados = document.getElementById("numero_lesionadosM");
const cedula_lesionado = document.getElementById("cedula_lesionadoM");
const recurso_utilizado = document.getElementById("recurso_utilizadoM");
const cantidad_recurso = document.getElementById("cantidad_recursoM");
const unidad = document.getElementById("unidadM");
const jefe_comision = document.getElementById("jefe_comisionM");
const efectivo = document.getElementById("efectivoM");
const ci_pnb = document.getElementById("ci_pnbM");
const ci_gnb = document.getElementById("ci_gnbM");
const ci_intt = document.getElementById("ci_inttM");
const ci_invity = document.getElementById("ci_invityM");
const ci_pc = document.getElementById("ci_pcM");
const ci_otros = document.getElementById("ci_otrosM");
const observaciones = document.getElementById("observacionesM");
const modal = document.getElementById("modalM");

filas.forEach(fila => {

    fila.addEventListener("click",(e)=>{
       const columnas = fila.children
       id.value = columnas[0].textContent
       fecha.value = columnas[1].textContent
       seccion.value = columnas[2].textContent
       estacion.value = columnas[3].textContent
       tipo_aviso.value = columnas[4].textContent
       solicitante.value = columnas[5].textContent
       receptor.value = columnas[6].textContent
       aprobador.value = columnas[7].textContent
       hora_aviso.value = columnas[8].textContent
       hora_salida.value = columnas[9].textContent
       hora_llegada.value = columnas[10].textContent
       hora_regreso.value = columnas[11].textContent
       municipio.value = columnas[12].textContent
       localidad.value = columnas[13].textContent
       direccion.value = columnas[14].textContent
       material_paredes.value = columnas[15].textContent
       material_techo.value = columnas[16].textContent
       material_piso.value = columnas[17].textContent
       material_ventanas.value = columnas[18].textContent
       material_puertas.value = columnas[19].textContent
       otros_materiales.value = columnas[20].textContent
       propietario.value = columnas[21].textContent
       valor_inmueble.value = columnas[22].textContent
       residenciados.value = columnas[23].textContent
       ninos.value = columnas[24].textContent
       adolescentes.value = columnas[25].textContent
       adultos.value = columnas[26].textContent
       informacion_adicional.value = columnas[27].textContent
       asegurado.value = columnas[28].textContent
       aseguradora.value = columnas[29].textContent
       numero_poliza.value = columnas[30].textContent
       valor_asegurado.value = columnas[31].textContent
       valor_perdido.value = columnas[32].textContent
       valor_salvado.value = columnas[33].textContent
       fuente_ignicion.value = columnas[34].textContent
       causa_incendio.value = columnas[35].textContent
       lugar_inicio.value = columnas[36].textContent
       lugar_fin.value = columnas[37].textContent
       reignicion.value = columnas[38].textContent
       tipo_combustible.value = columnas[39].textContent
       declaracion.value = columnas[40].textContent
       lesion.value = columnas[41].textContent
       numero_lesionados.value = columnas[42].textContent
       cedula_lesionado.value = columnas[43].textContent
       recurso_utilizado.value = columnas[44].textContent
       cantidad_recurso.value = columnas[45].textContent
       unidad.value = columnas[46].textContent
       jefe_comision.value = columnas[47].textContent
       efectivo.value = columnas[48].textContent
       ci_pnb.value = columnas[49].textContent
       ci_gnb.value = columnas[50].textContent
       ci_intt.value = columnas[51].textContent
       ci_invity.value = columnas[52].textContent
       ci_pc.value = columnas[53].textContent
       ci_otros.value = columnas[54].textContent
       observaciones.value = columnas[55].textContent
       console.log(columnas);
    });
});

// Detener la propagación del evento de clic cuando se hace clic en el modal
modal.addEventListener('click', (e) =>{
    e.stopPropagation();
});